### ISSUE TITLE
what's the problem?

### ISSUE THREAD

**Issue by SouthHalfCents** [MITRECND/libnids#5]
[root@centos65 home]# g++ test.cpp -lpcap -lnet -lnids -lgthread-2.0
test.cpp: 在函数‘int main()’中:
test.cpp:195:44: 错误：从类型‘void (*)(tcp_stream*, void**)’到类型‘void*’的转换无效 [-fpermissive]
     nids_register_tcp(tcp_protocol_callback);
                                            ^
In file included from test.cpp:1:0:
/usr/local/include/nids.h:149:6: 附注：initializing argument 1 of ‘void nids_register_tcp(void*)’
 void nids_register_tcp (void (*));

**Comment by vision57** [comment]
要么用C而不是C++来编写代码，并且用gcc而不是g++编译，要么在调用nids_register_tcp的时候把参数强转为void*类型。

**Comment by SouthHalfCents** [comment]
感谢！我刚才把头文件的声明改了用。。。
void nids_register_tcp(void (*tcp_func)(struct tcp_stream *ts, void **param));

**Comment by SouthHalfCents** [comment]
您发送的邮件我已经收到，我会尽快查看并回复 。 
//明夕何夕0x00 ***@***.***
